import axios from 'axios';
import { useEffect, useState } from 'react'
import Navbar from '../../components/Navbar';

const Shalat = () => {
    // Generated by https://quicktype.io
    const getDate = () => {
        const d = new Date()
        const month = (d.getMonth() + 1).toString().length < 2 ? "0" + (d.getMonth() + 1).toString() : (d.getMonth() + 1).toString()
        const date = d.getDate().toString().length < 2 ? "0" + d.getDate().toString() : d.getDate().toString()
        return (`${d.getFullYear()}-${month}-${date}`)
    }
    interface TopLevel {
        status: boolean;
        message: string;
        data: Data;
    }

    interface Data {
        id: string;
        kabko: string;
        prov: string;
        jadwal: Jadwal;
    }

    interface Jadwal {
        [key: string]: Today;
    }

    interface Today {
        tanggal: string;
        imsak: string;
        subuh: string;
        terbit: string;
        dhuha: string;
        dzuhur: string;
        ashar: string;
        maghrib: string;
        isya: string;
    }


    const [data, setData] = useState<Data>()
    useEffect(() => {
        axios.get<TopLevel>('https://api.myquran.com/v3/sholat/jadwal/58a2fc6ed39fd083f55d4182bf88826d/today')
            .then(data => {
                const fetched = data.data
                setData(fetched.data)
                console.log(fetched.data)
            })
        getDate()
    }, [])
    return (
        <>
            <Navbar />
            <main className=' col-6 mx-auto mt-5 rounded-4 p-4 shadow'>
                <p className=' fw-semibold text-center'>Jadwal shalat kota {data?.prov} hari {data?.jadwal[getDate()].tanggal}</p>

                {data && (
                    <table className=' table table-light table-striped table-hover'>
                        <thead>
                            <tr>
                                <th>Nama</th>
                                <th>Jadwal</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td> Imsak </td>
                                <td> {data?.jadwal[getDate()].imsak} </td>
                            </tr>
                            <tr>
                                <td> Shubuh </td>
                                <td> {data?.jadwal[getDate()].subuh} </td>
                            </tr>
                            <tr>
                                <td> Matahari Terbit </td>
                                <td> {data?.jadwal[getDate()].terbit} </td>
                            </tr>
                            <tr>
                                <td> Dhuha </td>
                                <td> {data?.jadwal[getDate()].dhuha} </td>
                            </tr>
                            <tr>
                                <td> Dzuhur </td>
                                <td> {data?.jadwal[getDate()].dzuhur} </td>
                            </tr>
                            <tr>
                                <td> Ashar </td>
                                <td> {data?.jadwal[getDate()].ashar} </td>
                            </tr>
                            <tr>
                                <td> Maghrib </td>
                                <td> {data?.jadwal[getDate()].maghrib} </td>
                            </tr>
                            <tr>
                                <td> Isya </td>
                                <td> {data?.jadwal[getDate()].isya} </td>
                            </tr>
                        </tbody>
                    </table>
                )}
            </main>
        </>
    )
}

export default Shalat