import axios from 'axios';
import { useEffect, useState } from 'react'

const Shalat = () => {
    // Generated by https://quicktype.io
    const getDate = () => {
        const d = new Date()
        const month = (d.getMonth() + 1).toString().length < 2 ? "0" + (d.getMonth() + 1).toString() : (d.getMonth() + 1).toString()
        const date = d.getDate().toString().length < 2 ? "0" + d.getDate().toString() : d.getDate().toString()
        return (`${d.getFullYear()}-${month}-${date}`)
    }
    interface TopLevel {
        status: boolean;
        message: string;
        data: Data;
    }

    interface Data {
        id: string;
        kabko: string;
        prov: string;
        jadwal: Jadwal;
    }

    interface Jadwal {
        [key: string]: Today;
    }

    interface Today {
        tanggal: string;
        imsak: string;
        subuh: string;
        terbit: string;
        dhuha: string;
        dzuhur: string;
        ashar: string;
        maghrib: string;
        isya: string;
    }


    const [data, setData] = useState<Data>()
    useEffect(() => {
        axios.get<TopLevel>('https://api.myquran.com/v3/sholat/jadwal/58a2fc6ed39fd083f55d4182bf88826d/today')
            .then(data => {
                const fetched = data.data
                setData(fetched.data)
                console.log(fetched.data)
            })
    }, [])
    console.log(getDate())
    return (
        <main className=' col-8 mx-auto mt-5'>
            <p>Jadwal shalat kota {data?.prov} tanggal {data?.jadwal[getDate()].tanggal}</p>
            {data && (
                <ul className=' list-group'>
                    <li className=' list-group-item'>
                        <span> Imsak </span>
                        <span> {data?.jadwal[getDate()].imsak} </span>
                    </li>
                    <li className=' list-group-item'>
                        <span> Shubuh </span>
                        <span> {data?.jadwal[getDate()].subuh} </span>
                    </li>
                    <li className=' list-group-item'>
                        <span> Matahari Terbit </span>
                        <span> {data?.jadwal[getDate()].terbit} </span>
                    </li>
                    <li className=' list-group-item'>
                        <span> Dhuha </span>
                        <span> {data?.jadwal[getDate()].dhuha} </span>
                    </li>
                    <li className=' list-group-item'>
                        <span> Dzuhur </span>
                        <span> {data?.jadwal[getDate()].dzuhur} </span>
                    </li>
                    <li className=' list-group-item'>
                        <span> Ashar </span>
                        <span> {data?.jadwal[getDate()].ashar} </span>
                    </li>
                    <li className=' list-group-item'>
                        <span> Maghrib </span>
                        <span> {data?.jadwal[getDate()].maghrib} </span>
                    </li>
                    <li className=' list-group-item'>
                        <span> Isya </span>
                        <span> {data?.jadwal[getDate()].isya} </span>
                    </li>
                </ul>
            )}
        </main>
    )
}

export default Shalat