// Generated by https://quicktype.io

export interface DataPesan {
    nama_pengirim: string;
    isi_pesan: string;
}
import data from '../assets/data/messages.json'
import '../assets/css/messages.css'
const Messages = () => {
    const msgData: DataPesan[] = data as DataPesan[]
    let i:number = 0
    setInterval(() => {
        i++
    }, 1000)
    return (
        <main className='d-flex justify-content-center align-items-start flex-column col-10 col-lg-8 mx-auto p-4 '>
            <div>
                <p className=" fs-5" style={{ textAlign: 'justify' }}>
                    "<i>{msgData[i].isi_pesan}</i>"
                </p>
                <p className=" fs-4 fw-light">~{msgData[i].nama_pengirim}</p>
            </div>
        </main>
    )
}

export default Messages