// Generated by https://quicktype.io

export interface DataPesan {
    nama_pengirim: string;
    isi_pesan: string;
}
import data from '../assets/data/messages.json'
import '../assets/css/messages.css'
import { useEffect, useState } from 'react';
const Messages = () => {
    const [num,setNum] = useState<number>(0)
    const msgData: DataPesan[] = data as DataPesan[]
    const randomize = (max:number) => {
        let res = Math.round(Math.random()*max)
        return res
    }
    useEffect(()=>{
        setNum(randomize(msgData.length))
    })
    return (
        <main className='d-flex justify-content-center align-items-start flex-column col-10 col-lg-8 mx-auto p-4 '>
            <div>
                <p className=" fs-5" style={{ textAlign: 'justify' }}>
                    "<i>{msgData[num]?.isi_pesan}</i>"
                </p>
                <p className=" fs-4 fw-light">~{msgData[num]?.nama_pengirim}</p>
            </div>
        </main>
    )
}

export default Messages