import axios from 'axios'
import React, { useEffect, useState } from 'react'
import Ayahbase from './Ayahbase';

const Readsurah = () => {
    interface DataSurah {
        number: number;
        name: string;
        englishName: string;
        englishNameTranslation: string;
        numberOfAyahs: number;
        revelationType: string;
    }
    // Generated by https://quicktype.io

    interface TopLevel {
        code: number;
        status: string;
        data: Data;
    }
    interface TopLevelTranslation {
        code: number;
        status: string;
        data: Data;
    }

    interface Data {
        number: number;
        name: string;
        englishName: string;
        englishNameTranslation: string;
        revelationType: string;
        numberOfAyahs: number;
        ayahs: Ayah[];
        edition: Edition;
    }

    interface DataTranslation {
        number: number;
        name: string;
        englishName: string;
        englishNameTranslation: string;
        revelationType: string;
        numberOfAyahs: number;
        ayahs: Translation[];
        edition: Edition;
    }

    interface Ayah {
        number: number;
        audio:string
        text: string;
        numberInSurah: number;
        juz: number;
        manzil: number;
        page: number;
        ruku: number;
        hizbQuarter: number;
        sajda: boolean;
    }

    interface Translation {
        number: number;
        text: string;
        numberInSurah: number;
        juz: number;
        manzil: number;
        page: number;
        ruku: number;
        hizbQuarter: number;
        sajda: boolean;
    }

    interface Edition {
        identifier: string;
        language: string;
        name: string;
        englishName: string;
        format: string;
        type: string;
        direction: string;
    }
    
    const [data, setData] = useState<DataSurah[]>()
    const [surah, setSurah] = useState<Data>()
    const [translation, setTranslation] = useState<DataTranslation>()
    useEffect(() => {
        axios.get('https://api.alquran.cloud/v1/surah')
            .then(data => {
                const fetched = data.data
                setData(fetched.data)
            })
    }, [])
    const handleSurah = (e: React.ChangeEvent<HTMLSelectElement>) => {
        axios.get<TopLevel>(`https://api.alquran.cloud/v1/surah/${e.target.value}/ar.alafasy`)
            .then(data => {
                const fetched = data.data
                setSurah(fetched.data)
            })
        axios.get<TopLevelTranslation>(`https://api.alquran.cloud/v1/surah/${e.target.value}/id.indonesian`)
            .then(data => {
                const fetched = data.data
                setTranslation(fetched.data)
            })
    }
    return (
        <main className=''>
            <div className="">
                {/* <label>Choose your surah</label> */}
                <select name="" id="" className=' form-select' onChange={(e) => handleSurah(e)}>
                    <option value="default" selected hidden>Pilih surat</option>
                    {data?.map(a => {
                        return (
                            <option value={a.number}>{a.englishName} ({a.englishNameTranslation}) , {a.numberOfAyahs}</option>
                        )
                    })}
                </select>
            </div>
            <section className=' mt-2'>
                {surah && (
                    <div className="shadow p-2 rounded-4 fs-5">
                        <div className=" d-flex flex-column">
                            <div className=" d-flex gap-2">
                                <p className='m-0 text-secondary'>{surah.name}</p>
                                <p className='m-0 fw-semibold'>{surah.englishName}</p>
                            </div>
                            <div className=" d-flex gap-2">
                                <p className='m-0'>{surah.revelationType}</p>
                                <p className='m-0'>{surah.numberOfAyahs} Ayat</p>
                            </div>
                        </div>
                        <section className=' mt-2'>
                            {translation && (
                                <Ayahbase data={surah.ayahs} dataIdn={translation.ayahs}/>
                            )}
                        </section>
                    </div>
                )}
            </section>
        </main>
    )
}

export default Readsurah